# Generated by Django 5.1.7 on 2025-03-31 23:19

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='perfil\x07vatar_padrao.png', null=True, upload_to=usuarios.models.caminho_foto_perfil),
        ),
    ]
