# Generated by Django 5.1.7 on 2025-04-01 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(blank=True, max_length=255)),
                ('editora', models.CharField(blank=True, max_length=255)),
                ('ano_publicacao', models.IntegerField(blank=True, null=True)),
                ('idioma', models.CharField(blank=True, max_length=50)),
                ('isbn', models.CharField(blank=True, max_length=50)),
                ('paginas', models.IntegerField(blank=True, null=True)),
                ('sinopse', models.TextField(blank=True)),
                ('capa_url', models.URLField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
