# Generated by Django 5.1.7 on 2025-04-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='pagina_atual',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
