# Generated by Django 5.1.7 on 2025-04-01 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessoes', '0002_sessaoleitura_pagina_atual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessaoleitura',
            name='pagina_atual',
        ),
    ]
